# Site settings
title: 河陰寶樹堂
email: yuanchen.gm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  備忘與分享。
  關於謝元辰的生活。
  追求古典與現代，不止於技術。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erstern.github.io" # the base hostname & protocol for your site
twitter_username: yuanchensieh
github_username:  erstern

# Build settings
#markdown: rdiscount
markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
highlighter: true

# 開啓分頁功能
paginate: 5
paginate_path: "blog/page:num"
