# Site settings
title: 元辰在github的山頭
email: yuanchen.gm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erstern.github.io" # the base hostname & protocol for your site
twitter_username: yuanchensieh
github_username:  erstern

# Build settings
markdown: kramdown
